name=SensorAndHudSharedCode
version=1.0.0
author=Chris
maintainer=Chris
sentence=Shared workspace core libraries.
paragraph=Single instance code repository portal.
category=Utility
url=
architectures=esp32
